---
title: "Homework-03"
author: "Yaasiel Leos Ledesma"
format: html
editor: visual
date: 2026-02-28 
---

[GitHub Repository](https://github.com/yaasiell/ENVS-193DS_homework-03.git)

```{r}
#| label: Read in Packages and Data
#| message: false
#| warning: false
# Loading in required packages
library (tidyverse) # data wrangling and plotting
library(here) # direct file paths to call from
library(janitor) # to examine and read in data
library(readxl) # reads excel files

# create new object called salinity to call from our data file
salinity <- read.csv(here("data",
                     "salinity-pickleweed.csv"))
# my_data_commute as new object for my logged commute data
my_data_commute <- read.csv(here("data","updated_commute.csv")) |>
clean_names() # cleans column names to be used in ggplot

# my_data_skateboard as new object for my logged skateboard
my_data_skateboard <- read.csv(here("data","updated_skateboard.csv")) |>
  clean_names() # cleans skateboard data columns to correct format
```

# Problem 1. Slough soil salinity

## a. An appropriate test

[The appropriate tests to determine the strength of the relationship between salinity and California pickle weed biomass would be the Pearson's correlation and Spearman's rank correlation. Pearson's correlation differs because it is used when two continuous variables have a linear relationship and are normally distributed with the data meeting its assumptions of normality and independence. Spearman's correlations is different because it is non-parametric and based on ranks that is more helpful in a monotonic relationship between variables instead of a linear relationship. ]

## b. Create a visualization

```{r}
#| label: Creating a visualization for relationship between salinity and pickleweed biomass
# create a visualization for the relationship between salinity and pickleweed mass
ggplot(data = salinity, # calls for salinity data set
       aes(x = salinity_mS_cm, # calls for assigning salinity column data to x-axis
           y = pickleweed # calls for assigning pickle weed column data to y-axis
           )) +
  geom_point(color = "dodgerblue3", # plot data as points and change color
             size = 3) + # change the size for each data point
  labs(x = "Soil Salinity (mS/cm)", # call for labels and names x-axis with measurements
       y = "Pickelweed biomass (g)", # label for y-axis with measurements
       #label for title of the graph
       title = "Relationship between Pickleweed biomass and Soil Salinity" 
  ) +
  theme_get() # changes theme different from the default 


```

